version: '3.4'

services:
  angularui:
    #container_name: angular_ui_container
    build:
      context: .
      dockerfile: ./DockerWeb/Dockerfile
    volumes:
      - './DockerWeb:/usr/src/app'
    ports:
      - 4200:4200
  dockerapi:
    image: ${DOCKER_REGISTRY}dockerapi
    #container_name: my_api_container
    build:
      context: .
      dockerfile: ./DockerApi/Dockerfile
    environment:
      SQLSERVER_HOST: db
      SA_PASSWORD: Ajeesh250282
    #expose:
     # - 80
    ports:
      - 4300:80
    depends_on:
      - db
  flyway:
    image: boxfuse/flyway
    #container_name: flyway_container
    command: -url=jdbc:jtds:sqlserver://db -user=sa -password=Ajeesh250282 -connectRetries=300 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
  db:
    image: "microsoft/mssql-server-linux:2017-latest"
    #container_name: linuxsqlcontainer
    ports:
      - 1436:1433
    environment:
      SA_PASSWORD: Ajeesh250282
      ACCEPT_EULA: Y
 